# Generated by Django 5.2.1 on 2025-06-02 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Minha_tarefa",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("lista_tarefa", models.CharField(max_length=100)),
                ("O_que_Aprendeu", models.CharField(max_length=10000000)),
            ],
        ),
    ]
