# Generated by Django 5.2.1 on 2025-06-11 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tarefas", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Vaga",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=200)),
                ("empresa", models.CharField(max_length=200)),
                ("localizacao", models.CharField(blank=True, max_length=100)),
                ("descricao", models.TextField()),
                ("data_publicacao", models.DateField(auto_now_add=True)),
                ("link_candidatura", models.URLField(max_length=500)),
                (
                    "imagem",
                    models.ImageField(
                        blank=True, null=True, upload_to="Imagens_empresas/"
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="Minha_tarefa",
        ),
    ]
