# Generated by Django 5.2.1 on 2025-06-12 18:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tarefas", "0002_vaga_delete_minha_tarefa"),
    ]

    operations = [
        migrations.AddField(
            model_name="vaga",
            name="data_limite",
            field=models.DateField(default=datetime.date(2025, 6, 12)),
        ),
    ]
