# Generated by Django 5.2.1 on 2025-06-14 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tarefas", "0003_vaga_data_limite"),
    ]

    operations = [
        migrations.CreateModel(
            name="Curso",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("instituicao", models.CharField(max_length=200)),
                ("Nome_curso", models.CharField(max_length=200)),
                (
                    "imagem",
                    models.ImageField(blank=True, null=True, upload_to="Imagem_curso"),
                ),
                ("Descricao_curso", models.TextField()),
                ("inscricao", models.TextField()),
                ("inicio_inscricao", models.DateField(auto_now_add=True)),
                (
                    "limite_inscricao",
                    models.DateField(verbose_name="data limite de candidatura"),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="vaga",
            name="data_limite",
            field=models.DateField(verbose_name="data limite de candidatura"),
        ),
    ]
