# Generated by Django 5.2.1 on 2025-06-15 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tarefas", "0004_curso_alter_vaga_data_limite"),
    ]

    operations = [
        migrations.CreateModel(
            name="Cursar",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("instituicao", models.CharField(max_length=200)),
                ("Nome_curso", models.CharField(max_length=200)),
                (
                    "imagem",
                    models.ImageField(blank=True, null=True, upload_to="Imagem_curso"),
                ),
                ("Descricao_curso", models.TextField()),
                ("requisitos", models.TextField()),
                ("inscricao", models.TextField()),
                ("mensalidade", models.TextField()),
                ("inicio_inscricao", models.DateField(auto_now_add=True)),
                (
                    "limite_inscricao",
                    models.DateField(verbose_name="data limite de candidatura"),
                ),
                (
                    "palavrsa_chave",
                    models.TextField(
                        verbose_name="Palavras chaves (separadas por virgula)"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="empregar",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("empresa", models.TextField(max_length=200)),
                ("titulo", models.TextField(max_length=200)),
                ("Descricao", models.CharField(max_length=500)),
                ("responsabilidades", models.TextField()),
                ("requisitos", models.CharField()),
                ("processo_candidatura", models.EmailField(max_length=254)),
                ("data_de_publicacao", models.DateField(auto_now_add=True)),
                ("data_limite", models.DateField()),
                (
                    "imagem",
                    models.ImageField(blank=True, null=True, upload_to="Imagem_vaga"),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="Curso",
        ),
        migrations.DeleteModel(
            name="Vaga",
        ),
    ]
