# Generated by Django 5.2.1 on 2025-06-15 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tarefas", "0005_cursar_empregar_delete_curso_delete_vaga"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cursar",
            name="Descricao_curso",
            field=models.TextField(verbose_name=200),
        ),
        migrations.AlterField(
            model_name="cursar",
            name="inscricao",
            field=models.TextField(max_length=20),
        ),
        migrations.AlterField(
            model_name="cursar",
            name="mensalidade",
            field=models.TextField(max_length=20),
        ),
    ]
