# Generated by Django 5.2.1 on 2025-06-15 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "tarefas",
            "0006_alter_cursar_descricao_curso_alter_cursar_inscricao_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="cursar",
            name="Descricao_curso",
            field=models.TextField(max_length=200),
        ),
    ]
