# Generated by Django 5.2.1 on 2025-06-17 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tarefas", "0007_alter_cursar_descricao_curso"),
    ]

    operations = [
        migrations.AlterField(
            model_name="empregar",
            name="empresa",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="empregar",
            name="titulo",
            field=models.CharField(max_length=200),
        ),
    ]
