# Generated by Django 5.2.1 on 2025-06-17 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarefas', '0008_alter_empregar_empresa_alter_empregar_titulo'),
    ]

    operations = [
        migrations.AddField(
            model_name='empregar',
            name='localizacao',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='empregar',
            name='empresa',
            field=models.CharField(max_length=200, verbose_name='Nome da empresa'),
        ),
        migrations.AlterField(
            model_name='empregar',
            name='titulo',
            field=models.CharField(max_length=200, verbose_name='Area de atuacao'),
        ),
    ]
