# Generated by Django 5.2.1 on 2025-06-17 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tarefas", "0009_empregar_localizacao_alter_empregar_empresa_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="empregar",
            name="localizacao",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
