# Generated by Django 5.2.1 on 2025-06-17 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tarefas", "0010_alter_empregar_localizacao"),
    ]

    operations = [
        migrations.AddField(
            model_name="empregar",
            name="site",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="empregar",
            name="processo_candidatura",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name="empregar",
            name="requisitos",
            field=models.TextField(),
        ),
    ]
