# Generated by Django 5.2.1 on 2025-06-17 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tarefas", "0011_empregar_site_alter_empregar_processo_candidatura_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="cursar",
            name="email_contato",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name="cursar",
            name="localizacao",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="cursar",
            name="site",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="cursar",
            name="Descricao_curso",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="cursar",
            name="Nome_curso",
            field=models.CharField(max_length=200, verbose_name="Nome do curso"),
        ),
        migrations.AlterField(
            model_name="cursar",
            name="inscricao",
            field=models.IntegerField(max_length=20, verbose_name="Valor da inscricao"),
        ),
        migrations.AlterField(
            model_name="cursar",
            name="mensalidade",
            field=models.IntegerField(
                max_length=20, verbose_name="Valor da mensalidade"
            ),
        ),
    ]
