# Generated by Django 5.2.1 on 2025-06-17 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "tarefas",
            "0012_cursar_email_contato_cursar_localizacao_cursar_site_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="cursar",
            name="inscricao",
            field=models.IntegerField(verbose_name="Valor da inscricao"),
        ),
        migrations.AlterField(
            model_name="cursar",
            name="mensalidade",
            field=models.IntegerField(verbose_name="Valor da mensalidade"),
        ),
    ]
