# Generated by Django 5.2.1 on 2025-06-18 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tarefas", "0013_alter_cursar_inscricao_alter_cursar_mensalidade"),
    ]

    operations = [
        migrations.AddField(
            model_name="cursar",
            name="Duracao",
            field=models.PositiveSmallIntegerField(
                blank=True, null=True, verbose_name="Duracao do Curso"
            ),
        ),
    ]
