# Generated by Django 5.2.1 on 2025-06-18 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tarefas", "0014_cursar_duracao"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cursar",
            name="localizacao",
            field=models.CharField(blank=True, null=True),
        ),
    ]
