# Generated by Django 5.2.1 on 2025-06-20 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tarefas", "0015_alter_cursar_localizacao"),
    ]

    operations = [
        migrations.AddField(
            model_name="cursar",
            name="banner",
            field=models.ImageField(blank=True, null=True, upload_to="banner"),
        ),
    ]
